### ISSUE TITLE
Unable to pipe the output to another tool

### ISSUE THREAD

**Issue by fabpot** [jlfwong/chrome2calltree#2]
I'm trying to use your tool to convert a Chrome CPU profile into callgrind to be able to upload it and visualize it on [Blackfire.io](https://blackfire.io/), which is an online alternative to KCacheGrind.

If I do something like this, it works well (https://blackfire.io/profiles/7c6f85ac-8ad2-4bae-bbe7-fda21eee858f/graph):

```
chrome2calltree -i some.cpuprofile > some.callgrind
blackfire --slot=2 upload some.callgrind
```

But using a pipe like this:

```
chrome2calltree -i some.cpuprofile | blackfire --slot=2 upload
```

triggers the following error:

```
Error: No file provided on the command line

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:905:11)
    at Object.afterWrite (net.js:721:19)
```

**Comment by jlfwong** [comment]
Not too sure offhand what would cause that, but I'm open to accepting PRs that fix the problem!
