### ISSUE TITLE
Node 0.12 issue with execSync

### ISSUE THREAD

**Issue by pete-the-pete** [jlfwong/chrome2calltree#3]
Chrome2calltree is suffering from execSync issue. https://github.com/mgutz/execSync/issues/38
The solution is probably to change to sync-exec.

I was able to get around the issue by installing an older version of node using nvm.

chrome2calltree 
module.js:338
    throw err;
          ^
Error: Cannot find module './build/Release/shell'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (~/.nvm/versions/v0.12.2/lib/node_modules/chrome2calltree/node_modules/execSync/index.js:30:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by paulirish** [comment]
Aye. I'm also facing this error.

**Comment by awstlaur** [comment]
For anyone who doesn't care about this tool launching graphical programs for you, I forked and removed the `execSync` dependency: https://github.com/awstlaur/chrome2calltree

**Comment by paulirish** [comment]
Jlfwong, please merge bump and publish .

**Comment by paulirish** [comment]
Lol sorry. Thank you!
